# This is a basic workflow to help you get started with Actions

name: Repo Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mirror"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote and calculate stats
        run: |
          echo "Local: $(git for-each-ref refs/remotes/origin | wc -l) branches, $(git for-each-ref refs/tags | wc -l) tags"
          git remote set-url origin "${{ secrets.upstream_repo }}"
          echo "Remote: $(git ls-remote origin 'refs/heads/*' | wc -l) branches, $(git ls-remote origin 'refs/tags/*' | wc -l) tags"

      # Runs a set of commands using the runners shell
      - name: Fetch branches and tags
        run: |
          git fetch --force origin 'refs/heads/*:refs/remotes/origin/*' 'refs/tags/*:refs/tags/*'
          echo "Local after fetch: $(git for-each-ref refs/remotes/origin | wc -l) branches, $(git for-each-ref refs/tags | wc -l) tags"

      - name: Push to downstream repo
        run: |
          git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
          git for-each-ref --format="%(refname)" --exclude refs/remotes/origin/HEAD refs/remotes/origin refs/tags | sed -E 's@^refs/remotes/origin/(.*)@refs/remotes/origin/\1:refs/heads/\1@g' | xargs -n 2000 git push origin
