# This is a basic workflow to help you get started with Actions

name: Repo Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  schedule:
    - cron:  '30 19 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mirror"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote and calculate stats
        run: |
          git for-each-ref --format="%(objectname)%09%(refname)" --exclude refs/remotes/origin/HEAD refs/remotes/origin refs/tags | sed -E 's@refs/remotes/origin/(.*)@refs/heads/\1@g' > git-refs-local.txt
          echo "Local: $(grep refs/heads git-refs-local.txt | wc -l) branches, $(grep refs/tags git-refs-local.txt | wc -l) tags"

          git remote set-url origin "${{ secrets.upstream_repo }}"

          git ls-remote origin 'refs/tags/*' 'refs/heads/*' | grep -Fv '^{}' | tee git-refs-remote.txt
          echo "Remote: $(grep refs/heads git-refs-remote.txt | wc -l) branches, $(grep refs/tags git-refs-remote.txt | wc -l) tags"

      # Runs a set of commands using the runners shell
      - name: Fetch branches and tags
        run: |
          git fetch --force origin 'refs/heads/*:refs/remotes/origin/*' 'refs/tags/*:refs/tags/*'

      - name: Push to downstream repo
        continue-on-error: true
        run: |
          git for-each-ref --format="%(objectname)%09%(refname)" --exclude refs/remotes/origin/HEAD refs/remotes/origin refs/tags | sed -E 's@refs/remotes/origin/(.*)@refs/heads/\1@g' > git-refs-local-fetched.txt
          echo "Local after fetch: $(grep refs/heads git-refs-local-fetched.txt | wc -l) branches, $(grep refs/tags git-refs-local-fetched.txt | wc -l) tags"

          diff -e git-refs-local.txt git-refs-remote.txt | grep '\t' > git-refs-updated.txt
          echo "To be updated: $(grep refs/heads git-refs-updated.txt | wc -l) branches, $(grep refs/tags git-refs-updated.txt | wc -l) tags"

          git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
          cut -f2 < git-refs-updated.txt | sed -E 's@^refs/heads/(.*)@refs/remotes/origin/\1:refs/heads/\1@g' | xargs -n 2000 git push --force origin

      - name: Upload git-refs for reference
        uses: actions/upload-artifact@v4.6.0
        with:
          name: git-refs-log
          path: git-refs-*
